### ISSUE TITLE
What is the rationale for this?

### ISSUE THREAD

**Issue by emilydaemon** [Zuper64/wii-homebrew#3]
There are already two Wii modding guides, one of which is basically replacing the other (https://wii.hacks.guide/ and https://wii.guide/).
I don't see a reason to make another Wii modding guide, especially one that, from a quick peek at the project, seems to mostly be a 1:1 copy of the contents of the aforementioned guides.
In addition, there is no reason to write your own WiiLink guide; there is already one maintained by the WiiLink developers. It's best to simply link to the official guide rather than to maintain your own guide, which may end up breaking or becoming outdated.

**Comment by SammyGoesHowdy** [comment]
I agree

**Comment by DardelHMB** [comment]
Not to mention the wiilink guide here is outdated; the wiilink patcher is not a shell script anymore.

**Comment by QRSFirestorm** [comment]
> There are already two Wii modding guides, one of which is basically replacing the other (https://wii.hacks.guide/ and https://wii.guide/). I don't see a reason to make another Wii modding guide, especially one that, from a quick peek at the project, seems to mostly be a 1:1 copy of the contents of the aforementioned guides. In addition, there is no reason to write your own WiiLink guide; there is already one maintained by the WiiLink developers. It's best to simply link to the official guide rather than to maintain your own guide, which may end up breaking or becoming outdated.

Its just a project, if you have a problem with it you are welcome to leave. Simple as that.

**Comment by emilydaemon** [comment]
> Its just a project, if you have a problem with it you are welcome to leave. Simple as that.

You still haven't answered any of my questions. As one of the contributors of both wii.guide and wii.hacks.guide, I find it appalling that mine and many other people's work has been copied so blatantly.
This project is not only immoral, but also potentially harmful to the homebrew community.
If I have made any mistakes in any of my comments, please correct me; however, the fact that your response didn't address any of my claims, I have basically no choice other than to assume that I am correct.

**Comment by SammyGoesHowdy** [comment]
> Its just a project, if you have a problem with it you are welcome to leave. Simple as that.

This is a fairly immature way to go about this... ¯\_(ツ)_/¯

**Comment by IceLapras** [comment]
> > Its just a project, if you have a problem with it you are welcome to leave. Simple as that.
> 
> You still haven't answered any of my questions. As one of the contributors of both wii.guide and wii.hacks.guide, I find it appalling that mine and many other people's work has been copied so blatantly.
> This project is not only immoral, but also potentially harmful to the homebrew community.
> If I have made any mistakes in any of my comments, please correct me; however, the fact that your response didn't address any of my claims, I have basically no choice other than to assume that I am correct.

Well, while I do get your point, calling them blatant copies is not really correct.
First off, this project is just for fun. (And it's not finished yet, so of course there are mistakes.) Second, the guides may look similar because they are talking about the same thing, so I find it pretty obvious that they could look this way.

**Comment by Zuper64** [comment]
> There are already two Wii modding guides, one of which is basically replacing the other (https://wii.hacks.guide/ and https://wii.guide/).
> I don't see a reason to make another Wii modding guide, especially one that, from a quick peek at the project, seems to mostly be a 1:1 copy of the contents of the aforementioned guides.
> In addition, there is no reason to write your own WiiLink guide; there is already one maintained by the WiiLink developers. It's best to simply link to the official guide rather than to maintain your own guide, which may end up breaking or becoming outdated.

I'm just making it for fun.

And many of the guides are reused from an old project I helped work on, which would be why the Wiilink guide is outdated... I'll update it to just a link to the official guide.
